version: "3"

services:
  # db:
  #   container_name: core_db
  #   image: postgres:12.3
  #   restart: always
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   env_file: ./.env.docker
  #   networks:
  #     - servernet

  server:
    container_name: core_server
    image: nadib/scraperworld-backend:main
    expose:
      - 8000
    volumes:
      - media_data:/app/media
      - static_data:/app/static
    env_file:
      - .env
    # depends_on:
    #   - db
    # links:
    #   - db:db

  # nginx:
  #   container_name: nginx
  #   build: ./nginx
  #   restart: always
  #   ports:
  #     - 8080:80
  #   depends_on:
  #     - server
  #   volumes:
  #     - media_data:/media
  #     - static_data:/static

volumes:
  media_data:
  static_data:
  postgres_data:
