# Generated by Django 3.2.20 on 2023-10-06 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='user_name'),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='phone_number',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
